_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 105
            "3":
                - 55
            "4": 3.12.7
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
